name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files #In order to use ls or any files command we need to use the checkout aciton.
                         #github.com/actions/checkout
        run: | 
          pwd
          ls 
          echo $GITHUB_SHA
          echo $GITHUB_RESPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github}}"
      - name: checkout
        uses: actions/checkout@v3
      - name: List Files 
        run: |
          pwd
          ls 
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1 #Can also use @tag, @branch and @commit_id
        with: #input to action.
          who-to-greet: Byron
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"



# Environment Variables
# $GITHUB_SHA: The commit id that triggered this workflow to run.
# $GITHUB_RESPOSITORY: The username and repo name
# $GITHUB_WORKSPACE: The github working directory (/home/runner/work/{repo}/{repo})