name: shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: eccho "Hello World"
      - name: multiline scirpt
        run: | 
          node -v
          npm -v